### ISSUE TITLE
Tracking information is not described in the user guide

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/ofn-UserGuide#22]
## Admin Only: Language Checklist for when this Update is Complete
- [ ] English
- [ ] French
- [ ] Catalan
- [ ] Italian
- [ ] Russian
- [ ] Turkish
- [ ] Spanish
- [ ] Portuguese
- [ ] German

----------------------------------------------------------------------------------------------------------------
## Tell us what you would like to see
There should be an explanation what the "tracking" field is for on the admin/orders/Rxxx/edit page and where this information will be displayed.

**Which language version of the User Guide are you viewing?**
English

**Description**
Explanation of the tracking field on the admin/orders/Rxxx/edit page and where this information will be displayed.

**Which section would you like the new content to be added to?**
- [ ] Quick Start Guide
- [x] Features 
- [ ] Hub Management Tips (How to's)
- [ ] Troubleshooting
- [ ] Glossary
- [ ] other- please state:

**If 'Features' please state the subsection here**
orders - view orders - editing an order

**In which instance(s) do you know that users are adversely affected by this information being missing from the User Guide in its current form?**
Germany

**How would you rate the impact of the current version of the User Guide on your instance?**
- [ ] High volume of support queries
- [x] Occasional support query
- [ ] Prevents/deters new enterprises from setting up
- [ ] User misunderstandings around this issue result in those enterprises affected moving away from OFN...

**Suggested Draft of content to be added**
t.b.d.

**I would like to be part of a larger User Guide group who write this section**
- [x] yes
- [ ] no

**Additional Context**
